# Defines the stages of the pipeline
stages:
  - build
  - publish

# Specify a Maven with Java 11 use in the pipeline
# image: maven:3.8.6-eclipse-temurin-17

variables:
  # set to use .m2/repository
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"
  # ensure compatibility
  DOCKER_DRIVER: overlay2

# Cache Maven dependencies to speed up the build process
cache:
  key: "$CI_JOB_NAME"
  paths:
    - $CI_PROJECT_DIR/.m2/repository

# Build Stage: Run Maven to build and package the application
build:
  stage: build
  image: maven:3.8.6-eclipse-temurin-17
  # Maven image with JDK
  script:
    - echo "Building the project with Maven..."
    - mvn clean install -X -DskipTests
  artifacts:
    paths:
      - target/*.jar
  only:
    - master

# Package Stage: Build Docker image
publish:
  stage: publish
  image: docker:latest
  # Enables Docker in Docker
  services:
    - docker:24.0-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  dependencies:
    - build
  script:
    - echo "Building Docker images..."
    - docker build -t $DOCKER_USERNAME/InsecureAPI:$CI_COMMIT_SHORT_SHA .
    - docker build -t $DOCKER_USERNAME/InsecureAPI:latest .
    - echo "Logging in to Docker..."
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - echo "Pushing Images to Docker Hub..."
    - docker push $DOCKER_USERNAME/InsecureAPI:$CI_COMMIT_SHORT_SHA
    - docker push $DOCKER_USERNAME/InsecureAPI:latest
  only:
    - master
