# This is a basic workflow that is manually triggered

name: Build and Deploy Jar file in Docker Repository

on:
  push:
    branches:
      - main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-jar:
    runs-on: ubuntu-latest
    environment: InsecureAPI_env
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Checkout Repository
      uses: actions/checkout@v3

      # Use a specific Java version to build the application
    - name: Set up JDK 21
      uses: actions/setup-java@v3
      with:
          java-version: '21'
          distribution: 'temurin'

    - name: Build the Java application
      run: mvn clean install

    - name: Upload JAR Artifact
      uses: actions/upload-artifact@v3
      with:
        name: insecureapi
        path: target/InsecureAPI-1.0.0.jar
        if-no-files-found: warn
        include-hidden-files: false

    - name: Build latest image
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/InsecureApi:latest .

    - name: Version tagged images
      run: docker build -t ${{ secrets.DOCKER_USERNAME }}/InsecureApi:1.0.0 .

    - name: Login to docker
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # Push the Docker image to Docker Hub
    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/insecureapi:1.0.0

    - name: Push Docker image to Docker Hub
      run: docker push ${{ secrets.DOCKER_USERNAME }}/insecureapi:latest
